#!/bin/bash

###############################################################################
##  Author:       Adam Wright
##  Email:        wrighada@oregonstate.edu
##  Date:         5-23-2020
##  Description:  Bash shell script to compile program 4 for OSU cs344 Spring
##                2020.
###############################################################################

# GNU compilation commands for each program
gcc -o keygen keygen.c
gcc -o otp otp.c
gcc -o otp_d otp_d.c
